"""
Frame Manipulation Tool
Flow: Grounding DINO bbox → logo centered on object → Nova Canvas blends edges
"""
import boto3
import json
import base64
import os
from typing import Dict, Any
from PIL import Image, ImageDraw
import io
import cv2
import numpy as np
from botocore.config import Config
from config import NOVA_CANVAS_MODEL_ID, AWS_REGION, BASE_DIR

bedrock = boto3.client(
    'bedrock-runtime',
    region_name=AWS_REGION,
    config=Config(read_timeout=300)
)

_MODELS_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'models')
_SEG_MODEL_PATH = os.path.join(_MODELS_DIR, 'yolov8n-seg.pt')


def decode_base64_to_image(base64_string: str) -> Image.Image:
    image_data = base64.b64decode(base64_string)
    return Image.open(io.BytesIO(image_data))


def resize_for_nova_canvas(image: Image.Image, max_dim: int = 1408) -> tuple:
    """
    Resize image to fit Nova Canvas requirements:
    - Each side between 320-4096px, divisible by 16, aspect ratio 1:4 to 4:1
    Returns (resized_image, scale_factor)
    """
    width, height = image.size
    if width > max_dim or height > max_dim:
        scale = min(max_dim / width, max_dim / height)
        new_width = int(width * scale)
        new_height = int(height * scale)
    else:
        scale = 1.0
        new_width, new_height = width, height

    new_width = max(320, (new_width // 16) * 16)
    new_height = max(320, (new_height // 16) * 16)

    if new_width != width or new_height != height:
        resized = image.resize((new_width, new_height), Image.Resampling.LANCZOS)
        return resized, new_width / width

    return image, 1.0


def create_edge_mask_from_bbox(image_size: tuple, bbox: list, edge_width: int = 20) -> Image.Image:
    """
    Outer-ring mask for Nova Canvas blending.
    BLACK (inpaint) = ring of surface pixels SURROUNDING the logo.
    WHITE (preserve) = the logo itself + everything else.
    Nova Canvas blends the surface around the logo without ever touching the logo pixels.
    """
    width, height = image_size
    mask = Image.new('RGB', (width, height), (255, 255, 255))

    x = int(bbox[0] * width / 100)
    y = int(bbox[1] * height / 100)
    w = int(bbox[2] * width / 100)
    h = int(bbox[3] * height / 100)

    # Black ring outside the logo
    outer_x = max(0, x - edge_width)
    outer_y = max(0, y - edge_width)
    outer_x2 = min(width, x + w + edge_width)
    outer_y2 = min(height, y + h + edge_width)

    draw = ImageDraw.Draw(mask)
    draw.rectangle([outer_x, outer_y, outer_x2, outer_y2], fill=(0, 0, 0))

    # White over the logo itself — fully preserved
    draw.rectangle([x, y, x + w, y + h], fill=(255, 255, 255))

    return mask


def blend_overlay_edges(frame_path: str, bbox: list, output_path: str, edge_width: int = 25) -> str:
    """
    Use Nova Canvas inpainting to seamlessly blend the logo edges into the frame.
    """
    original_image = Image.open(frame_path).convert('RGB')
    original_size = original_image.size
    resized_image, scale = resize_for_nova_canvas(original_image)
    scaled_edge_width = max(15, int(edge_width * scale))

    img_buffer = io.BytesIO()
    resized_image.save(img_buffer, format='PNG')
    image_base64 = base64.b64encode(img_buffer.getvalue()).decode('utf-8')

    mask = create_edge_mask_from_bbox(resized_image.size, bbox, scaled_edge_width)
    mask_buffer = io.BytesIO()
    mask.save(mask_buffer, format='PNG')
    mask_base64 = base64.b64encode(mask_buffer.getvalue()).decode('utf-8')

    request_body = {
        "taskType": "INPAINTING",
        "inPaintingParams": {
            "image": image_base64,
            "maskImage": mask_base64,
            "text": "seamless blend, match scene lighting and shadows, realistic surface texture, natural illumination, photorealistic integration"
        },
        "imageGenerationConfig": {
            "numberOfImages": 1,
            "height": resized_image.height,
            "width": resized_image.width,
            "cfgScale": 6.0
        }
    }

    response = bedrock.invoke_model(modelId=NOVA_CANVAS_MODEL_ID, body=json.dumps(request_body))
    response_body = json.loads(response['body'].read())

    if response_body.get("error"):
        raise Exception(f"Nova Canvas error: {response_body.get('error')}")

    if 'images' in response_body and response_body['images']:
        result_image = decode_base64_to_image(response_body['images'][0])
        if scale != 1.0:
            result_image = result_image.resize(original_size, Image.Resampling.LANCZOS)
        result_image.save(output_path, 'JPEG', quality=95)
        return output_path

    raise Exception("No image generated by Nova Canvas")


def bbox_to_pixels(bbox: dict, width: int, height: int) -> tuple:
    """Convert {Left, Top, Width, Height} fractions to pixel (x, y, w, h)."""
    return (
        int(bbox["Left"] * width),
        int(bbox["Top"] * height),
        int(bbox["Width"] * width),
        int(bbox["Height"] * height)
    )


_seg_model = None


def _get_seg_model():
    global _seg_model
    if _seg_model is None:
        from ultralytics import YOLO
        print(f"Loading YOLO segmentation ({_SEG_MODEL_PATH})...")
        _seg_model = YOLO(_SEG_MODEL_PATH)
        print("YOLO segmentation loaded.")
    return _seg_model


def restore_foreground_occlusion(
    frame_img: Image.Image,
    original_frame_path: str,
    logo_x: int, logo_y: int, logo_w: int, logo_h: int
) -> Image.Image:
    """
    After pasting the logo, detect person/hand pixels (YOLO segmentation) in the
    original frame that overlap the logo area and restore them so the hand appears
    naturally in front of the logo instead of behind it.
    """
    try:
        model = _get_seg_model()
        results = model(original_frame_path, classes=[0], verbose=False)  # class 0 = person

        if not results or results[0].masks is None:
            return frame_img

        width, height = frame_img.size
        foreground = np.zeros((height, width), dtype=np.uint8)

        for mask in results[0].masks.data:
            mask_np = cv2.resize(mask.cpu().numpy(), (width, height))
            foreground = np.maximum(foreground, (mask_np > 0.5).astype(np.uint8))

        # Only restore pixels where the person overlaps the logo area
        logo_region = np.zeros((height, width), dtype=np.uint8)
        logo_region[logo_y:logo_y + logo_h, logo_x:logo_x + logo_w] = 1
        overlap = foreground & logo_region

        if not overlap.any():
            return frame_img

        original = Image.open(original_frame_path).convert('RGBA')
        frame_arr = np.array(frame_img)
        orig_arr = np.array(original)
        mask_4ch = np.stack([overlap] * 4, axis=-1)
        frame_arr = np.where(mask_4ch, orig_arr, frame_arr)
        return Image.fromarray(frame_arr, 'RGBA')

    except Exception as e:
        print(f"Occlusion restore failed: {e}")
        return frame_img


def find_surface_corners(frame_img_rgba: Image.Image, bx: int, by: int, bw: int, bh: int):
    """
    Detect the 4 corners of the surface within the bbox using edge detection.
    Returns np.float32 array [[TL], [TR], [BR], [BL]] in image coordinates,
    or None if a clean quadrilateral cannot be found (e.g. soft surfaces like clothing).
    """
    region = np.array(frame_img_rgba.convert('RGB'))[by:by + bh, bx:bx + bw]
    gray = cv2.cvtColor(region, cv2.COLOR_RGB2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    edges = cv2.Canny(blurred, 50, 150)

    contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return None

    largest = max(contours, key=cv2.contourArea)
    # Require the contour to cover at least 20% of the bbox area to avoid noise
    if cv2.contourArea(largest) < 0.2 * bw * bh:
        return None

    peri = cv2.arcLength(largest, True)
    for eps in [0.02, 0.03, 0.04, 0.05, 0.06]:
        approx = cv2.approxPolyDP(largest, eps * peri, True)
        if len(approx) == 4:
            break
    else:
        return None

    # Convert bbox-relative coords → image coords
    pts = approx.reshape(4, 2).astype(np.float32)
    pts[:, 0] += bx
    pts[:, 1] += by

    # Sort into [top-left, top-right, bottom-right, bottom-left]
    s = pts.sum(axis=1)
    d = np.diff(pts, axis=1).flatten()
    return np.float32([pts[np.argmin(s)], pts[np.argmin(d)],
                       pts[np.argmax(s)], pts[np.argmax(d)]])


def process_frame_with_strategy(
    frame_path: str,
    placement: dict,
    ads_mapping: dict,
    output_dir: str
) -> str:
    """
    Place an ad on a frame:
    - logo_swap: center logo on detected object bbox → Nova Canvas blends edges
    - surface_replacement: fill bbox with ad poster → Nova Canvas blends edges
    """
    ad_id = placement.get("ad_id")
    ad_info = ads_mapping.get(ad_id)
    if not ad_info:
        return None

    asset_path = ad_info.get("asset_local_path") or ad_info.get("asset_path")
    if not asset_path:
        return None
    if not os.path.isabs(asset_path):
        asset_path = os.path.join(BASE_DIR, asset_path)
    if not os.path.exists(asset_path):
        print(f"Asset not found: {asset_path}")
        return None

    raw_bbox = placement.get("bounding_box", {})
    if not raw_bbox:
        return None

    placement_type = placement.get("placement_type", "logo_swap")
    frame_name = os.path.basename(frame_path)
    output_path = os.path.join(output_dir, f"processed_{frame_name}")
    overlay_output = output_path.replace('.jpg', '_overlay.jpg')

    frame_img = Image.open(frame_path).convert('RGBA')
    width, height = frame_img.size
    bx, by, bw, bh = bbox_to_pixels(raw_bbox, width, height)

    if placement_type == "logo_swap":
        try:
            ad_img = Image.open(asset_path).convert('RGBA')
            ad_w, ad_h = ad_img.size

            # Nova Pro decides how much of the bbox the logo should fill
            logo_scale = float(placement.get("logo_scale", 0.5))
            logo_scale = max(0.1, min(1.0, logo_scale))
            scale = min(bw / ad_w, bh / ad_h) * logo_scale
            new_w = max(1, int(ad_w * scale))
            new_h = max(1, int(ad_h * scale))

            # Center on bbox center, clamped so the logo is never cut off by the frame edge
            cx = bx + bw // 2
            cy = by + bh // 2
            offset_x = max(0, min(width - new_w, cx - new_w // 2))
            offset_y = max(0, min(height - new_h, cy - new_h // 2))

            # Resize logo
            ad_resized = ad_img.resize((new_w, new_h), Image.Resampling.LANCZOS)

            # Blend scene ambient light onto the logo so it picks up the local color cast
            scene_patch = frame_img.crop(
                (offset_x, offset_y, offset_x + new_w, offset_y + new_h)
            ).convert('RGB')
            pixels = list(scene_patch.getdata())
            avg_r = int(sum(p[0] for p in pixels) / len(pixels))
            avg_g = int(sum(p[1] for p in pixels) / len(pixels))
            avg_b = int(sum(p[2] for p in pixels) / len(pixels))
            ambient = Image.new('RGBA', (new_w, new_h), (avg_r, avg_g, avg_b, 38))  # ~15% tint
            ad_resized = Image.alpha_composite(ad_resized, ambient)

            # Apply opacity so the logo feels printed-on rather than pasted
            r, g, b, a = ad_resized.split()
            a = a.point(lambda v: int(v * 0.85))
            ad_resized = Image.merge('RGBA', (r, g, b, a))

            # Try perspective warp to match the surface angle
            corners = find_surface_corners(frame_img, bx, by, bw, bh)
            if corners is not None:
                # Scale the quad down around its center by logo_scale
                center = corners.mean(axis=0)
                dst_pts = center + logo_scale * (corners - center)

                src_pts = np.float32([[0, 0], [new_w, 0], [new_w, new_h], [0, new_h]])
                M = cv2.getPerspectiveTransform(src_pts, dst_pts)

                logo_bgra = cv2.cvtColor(np.array(ad_resized), cv2.COLOR_RGBA2BGRA)
                warped = cv2.warpPerspective(logo_bgra, M, (width, height),
                                             flags=cv2.INTER_LANCZOS4)
                warped_pil = Image.fromarray(
                    cv2.cvtColor(warped, cv2.COLOR_BGRA2RGBA), 'RGBA'
                )
                frame_img.paste(warped_pil, (0, 0), warped_pil)

                # Bounding box of warped quad for Nova Canvas mask
                x_min, y_min = dst_pts.min(axis=0)
                x_max, y_max = dst_pts.max(axis=0)
                logo_bbox = [
                    max(0, x_min) / width * 100,
                    max(0, y_min) / height * 100,
                    (x_max - x_min) / width * 100,
                    (y_max - y_min) / height * 100
                ]
            else:
                # Flat surface or soft object — plain centered paste
                frame_img.paste(ad_resized, (offset_x, offset_y), ad_resized)
                logo_bbox = [
                    offset_x / width * 100,
                    offset_y / height * 100,
                    new_w / width * 100,
                    new_h / height * 100
                ]

            # Restore hand/foreground pixels so they appear in front of the logo
            lx = int(logo_bbox[0] * width / 100)
            ly = int(logo_bbox[1] * height / 100)
            lw = int(logo_bbox[2] * width / 100)
            lh = int(logo_bbox[3] * height / 100)
            frame_img = restore_foreground_occlusion(frame_img, frame_path, lx, ly, lw, lh)

            frame_img.convert('RGB').save(overlay_output, 'JPEG', quality=95)
            ad_img.close()

            # Nova Canvas blends the logo edges and lighting
            try:
                blend_overlay_edges(overlay_output, logo_bbox, output_path, edge_width=20)
                if os.path.exists(overlay_output):
                    os.remove(overlay_output)
            except Exception as e:
                print(f"Blend failed for logo_swap: {e}")
                if os.path.exists(overlay_output):
                    os.rename(overlay_output, output_path)

            return output_path

        except Exception as e:
            print(f"Logo swap failed: {e}")
            return None

    else:  # surface_replacement
        try:
            ad_img = Image.open(asset_path).convert('RGBA')
            ad_w, ad_h = ad_img.size

            corners = find_surface_corners(frame_img, bx, by, bw, bh)
            if corners is not None:
                # Warp poster to fit the exact detected quad of the surface
                src_pts = np.float32([[0, 0], [ad_w, 0], [ad_w, ad_h], [0, ad_h]])
                M = cv2.getPerspectiveTransform(src_pts, corners)
                ad_bgra = cv2.cvtColor(np.array(ad_img), cv2.COLOR_RGBA2BGRA)
                warped = cv2.warpPerspective(ad_bgra, M, (width, height),
                                             flags=cv2.INTER_LANCZOS4)
                warped_pil = Image.fromarray(cv2.cvtColor(warped, cv2.COLOR_BGRA2RGBA), 'RGBA')
                frame_img.paste(warped_pil, (0, 0), warped_pil)

                x_min, y_min = corners.min(axis=0)
                x_max, y_max = corners.max(axis=0)
                surface_bbox = [
                    max(0, x_min) / width * 100,
                    max(0, y_min) / height * 100,
                    (x_max - x_min) / width * 100,
                    (y_max - y_min) / height * 100
                ]
            else:
                # Fallback: fill the full bbox
                ad_resized = ad_img.resize((bw, bh), Image.Resampling.LANCZOS)
                frame_img.paste(ad_resized, (bx, by), ad_resized)
                surface_bbox = [
                    raw_bbox["Left"] * 100,
                    raw_bbox["Top"] * 100,
                    raw_bbox["Width"] * 100,
                    raw_bbox["Height"] * 100
                ]

            frame_img.convert('RGB').save(overlay_output, 'JPEG', quality=95)
            ad_img.close()
            try:
                blend_overlay_edges(overlay_output, surface_bbox, output_path, edge_width=25)
                if os.path.exists(overlay_output):
                    os.remove(overlay_output)
            except Exception as e:
                print(f"Blend failed for surface_replacement: {e}")
                if os.path.exists(overlay_output):
                    os.rename(overlay_output, output_path)

            return output_path

        except Exception as e:
            print(f"Surface replacement failed: {e}")
            return None


def save_frame_with_bbox(frame_path: str, bbox: list, output_dir: str, label: str = "") -> str:
    """Save a debug copy of the frame with bounding box drawn."""
    os.makedirs(output_dir, exist_ok=True)
    image = Image.open(frame_path).convert('RGB')
    w, h = image.size
    x = int(bbox[0] * w / 100)
    y = int(bbox[1] * h / 100)
    bw = int(bbox[2] * w / 100)
    bh = int(bbox[3] * h / 100)
    draw = ImageDraw.Draw(image)
    draw.rectangle([x, y, x + bw, y + bh], outline=(255, 0, 0), width=3)
    if label:
        draw.text((x + 5, y + 5), label, fill=(255, 0, 0))
    debug_path = os.path.join(output_dir, f"bbox_{os.path.basename(frame_path)}")
    image.save(debug_path, 'JPEG', quality=95)
    return debug_path


def draw_detection_mask(
    frame_path: str,
    placements: list,
    ads_mapping: dict,
    output_path: str
) -> str:
    """
    Draw a detection visualization on a frame for the hackathon demo video:
    - Semi-transparent colored fill over the detected bbox (mask effect)
    - Solid border outline
    - Label chip showing brand, object, and confidence

    Uses YOLO segmentation mask if available for a pixel-accurate shape,
    otherwise falls back to the bounding box rectangle.
    """
    frame = cv2.imread(frame_path)
    h, w = frame.shape[:2]

    # Accent color: vivid cyan-green
    COLOR = (0, 220, 120)

    for p in placements:
        bbox = p.get("bounding_box", {})
        if not bbox:
            continue

        x = int(bbox["Left"] * w)
        y = int(bbox["Top"] * h)
        bw = int(bbox["Width"] * w)
        bh = int(bbox["Height"] * h)

        ad_info = ads_mapping.get(p.get("ad_id"), {})
        brand = ad_info.get("brand", "Unknown")
        obj = p.get("target_object", "")
        conf = p.get("confidence", 0)

        # Try YOLO seg mask for pixel-accurate shape overlay
        mask_drawn = False
        try:
            model = _get_seg_model()
            results = model(frame_path, verbose=False)
            if results and results[0].masks is not None:
                best_mask = None
                best_overlap = 0
                for mask in results[0].masks.data:
                    mask_np = cv2.resize(mask.cpu().numpy(), (w, h))
                    mask_bin = (mask_np > 0.5).astype(np.uint8)
                    overlap = int(mask_bin[y:y + bh, x:x + bw].sum())
                    if overlap > best_overlap:
                        best_overlap = overlap
                        best_mask = mask_bin
                if best_mask is not None and best_overlap >= 0.1 * bw * bh:
                    overlay = frame.copy()
                    overlay[best_mask == 1] = (
                        overlay[best_mask == 1] * 0.5 +
                        np.array(COLOR[::-1], dtype=np.float32) * 0.5
                    ).astype(np.uint8)
                    cv2.addWeighted(overlay, 0.7, frame, 0.3, 0, frame)
                    contours, _ = cv2.findContours(best_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
                    cv2.drawContours(frame, contours, -1, COLOR, 2)
                    mask_drawn = True
        except Exception:
            pass

        if not mask_drawn:
            # Fallback: semi-transparent bbox fill
            overlay = frame.copy()
            cv2.rectangle(overlay, (x, y), (x + bw, y + bh), COLOR, -1)
            cv2.addWeighted(overlay, 0.35, frame, 0.65, 0, frame)
            cv2.rectangle(frame, (x, y), (x + bw, y + bh), COLOR, 2)

        # Label chip
        label = f"  {brand}  |  {obj}  {conf:.0%}  "
        font = cv2.FONT_HERSHEY_SIMPLEX
        font_scale = 0.55
        thickness = 1
        (lw, lh), baseline = cv2.getTextSize(label, font, font_scale, thickness)
        chip_y1 = max(0, y - lh - baseline - 8)
        chip_y2 = y
        chip_x2 = min(w, x + lw + 4)
        cv2.rectangle(frame, (x, chip_y1), (chip_x2, chip_y2), COLOR, -1)
        cv2.putText(frame, label, (x + 2, chip_y2 - baseline - 2),
                    font, font_scale, (0, 0, 0), thickness, cv2.LINE_AA)

    cv2.imwrite(output_path, frame)
    return output_path


def rekognition_bbox_to_percentages(bbox: dict) -> list:
    """Convert {Left, Top, Width, Height} fractions to [x, y, w, h] percentages."""
    return [bbox["Left"] * 100, bbox["Top"] * 100, bbox["Width"] * 100, bbox["Height"] * 100]
